language: ruby
cache: bundler
rvm:
- 2.5.5
before_install:
- gem install bundler -v 2.0.2
install:
- bundle install
script:
- rspec
deploy:
- provider: rubygems
  api_key:
    secure: >-
      Nt3cpkGoSueXvdIbe/TJPrWAI0gqBDTxlytYUNPLzrRPBsLVBrtvoPF+4KRbA69w9TfJZG2nd
      Fms319n17uXg77E5lcj5yzIwG75V/1/ZfA9C65kwlbF6LFoFWyPa9ZMXe7xoc+56n3FInuwY4
      GlBWK64o+4IdYG1zqNMKZHwLtdEdn4PwhfYV4y7yFWNboYuaSwiUNEfJYkq28R2RRdYEYffKl
      +1d+tsSgtgtne/6drketMJ7KYNeSNJuTcqtUZBnzlv0XZAkyCGvLCxelF8x5mDorgfAiX8G11
      TXCjQbKpdcZQucI6gU9PUZIud6WMUl/fFovYFL8QF0Zm8V9Ygua7S0wU3AVvDGL4Kv+dz5f1c
      B2Hyb/HheH/5aTfw9NKyt6nWQt0ngZdEUYlEpyjbTHsRTvSVrAMobiiI5YBE7fs7pxnbXpMpS
      rEZAWo8k6FRxTjcu9SqEP6599nyLTw7fvzoXyc0tpIlzXc7QRETNNA1T6jGjpjzNkQ/KHx6tg
      mYr6EHXV99lnfPA1TsxuBajt1nlGI7Hcvsxz5zovP8vP4ov7CoJ1KIZ9aF+YZ75OZ97cfOX8Z
      8PxhbtaYVz+TZiNuvzLkktgyuzTE2hHROcCstGH7rXpgs+c+bydc3xPORPzXgqNEZuHB6htup
      w+iNIMxU6PHAu8Bjezh3hnFyjk=
  gem: brutalismbot
  on:
    repo: brutalismbot/gem
    tags: true
