name: rspec

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: "11 21 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - 2.5.x
        - 2.6.x
        - 2.7.x

    steps:

    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: setup code climate
      uses: amancevice/code-climate-action@v0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        command: before-build

    - name: rspec
      run: |
        gem install bundler -v 2.1.2
        bundle install --jobs 4 --retry 3
        bundle exec rake

    - name: coverage
      uses: amancevice/code-climate-action@v0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        command: after-build -t simplecov
